name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Node for Allure CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Allure Commandline
        run: npm i -g allure-commandline
      - name: Run tests and collect Allure results
        run: |
          rm -rf reports/latest reports/.allure_results_tmp || true
          pytest test/ --color=yes --alluredir reports/.allure_results_tmp
      - name: Generate Allure HTML report
        run: allure generate reports/.allure_results_tmp -o reports/latest --clean
      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: reports/latest
      - name: Upload Allure results artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: reports/.allure_results_tmp